name: osint_recon_all
scope_required: true
mode: plan
sequence:
- module: osint.subdomain.amass
  purpose: auto
- module: osint.subdomain.subfinder
  purpose: auto
- module: osint.subdomain.assetfinder
  purpose: auto
- module: osint.subdomain.sublist3r
  purpose: auto
- module: osint.subdomain.findomain
  purpose: auto
- module: osint.subdomain.chaos_client
  purpose: auto
- module: osint.subdomain.sudomy
  purpose: auto
- module: osint.subdomain.domained
  purpose: auto
- module: osint.dns.massdns
  purpose: auto
- module: osint.dns.shuffledns
  purpose: auto
- module: osint.dns.dnsx
  purpose: auto
- module: osint.dns.puredns
  purpose: auto
- module: osint.dns.altdns
  purpose: auto
- module: osint.dns.knockpy
  purpose: auto
- module: osint.dns.dnsgen
  purpose: auto
- module: osint.dns.gotator
  purpose: auto
- module: osint.dns.ripgen
  purpose: auto
- module: osint.dns.alterx
  purpose: auto
- module: osint.dns.dnsenum
  purpose: auto
- module: osint.dns.fierce
  purpose: auto
- module: osint.takeover.subjack
  purpose: auto
- module: osint.takeover.subzy
  purpose: auto
- module: osint.takeover.tko_subs
  purpose: auto
- module: osint.scan.nmap
  purpose: auto
- module: osint.scan.masscan
  purpose: auto
- module: osint.scan.naabu
  purpose: auto
- module: osint.scan.rustscan
  purpose: auto
- module: osint.scan.sandmap
  purpose: auto
- module: osint.scan.scancannon
  purpose: auto
- module: osint.scan.zmap
  purpose: auto
- module: osint.scan.unicornscan
  purpose: auto
- module: osint.scan.nrich
  purpose: auto
- module: osint.web.httpx
  purpose: auto
- module: osint.web.httprobe
  purpose: auto
- module: osint.web.hakrawler
  purpose: auto
- module: osint.web.gospider
  purpose: auto
- module: osint.web.katana
  purpose: auto
- module: osint.web.gau
  purpose: auto
- module: osint.web.waybackurls
  purpose: auto
- module: osint.web.waymore
  purpose: auto
- module: osint.web.linkfinder
  purpose: auto
- module: osint.web.paramspider
  purpose: auto
- module: osint.web.arjun
  purpose: auto
- module: osint.web.kiterunner
  purpose: auto
- module: osint.web.cariddi
  purpose: auto
- module: osint.web.photon
  purpose: auto
- module: osint.web.paramminer
  purpose: auto
- module: osint.visual.aquatone
  purpose: auto
- module: osint.visual.eyewitness
  purpose: auto
- module: osint.visual.gowitness
  purpose: auto
- module: osint.visual.screenshoteer
  purpose: auto
- module: osint.visual.witnessme
  purpose: auto
- module: osint.visual.scrying
  purpose: auto
- module: osint.visual.httpscreenshot
  purpose: auto
- module: osint.visual.eyeballer
  purpose: auto
- module: osint.visual.depix
  purpose: auto
- module: osint.content.ffuf
  purpose: auto
- module: osint.content.dirsearch
  purpose: auto
- module: osint.content.feroxbuster
  purpose: auto
- module: osint.content.gobuster
  purpose: auto
- module: osint.content.dirb
  purpose: auto
- module: osint.content.dirbuster
  purpose: auto
- module: osint.content.wfuzz
  purpose: auto
- module: osint.tech.whatweb
  purpose: auto
- module: osint.tech.webanalyze
  purpose: auto
- module: osint.tech.wappalyzer
  purpose: auto
- module: osint.tech.wafw00f
  purpose: auto
- module: osint.tech.fingerprintx
  purpose: auto
- module: osint.tech.graphw00f
  purpose: auto
- module: osint.tech.cdncheck
  purpose: auto
- module: osint.tls.tlsx
  purpose: auto
- module: osint.tls.sslscan
  purpose: auto
- module: osint.tls.sslyze
  purpose: auto
- module: osint.tls.testssl
  purpose: auto
- module: osint.secrets.trufflehog
  purpose: auto
- module: osint.secrets.gitleaks
  purpose: auto
- module: osint.secrets.detect_secrets
  purpose: auto
- module: osint.secrets.shhgit
  purpose: auto
- module: osint.secrets.gitrob
  purpose: auto
- module: osint.secrets.git_secrets
  purpose: auto
- module: osint.secrets.noseyparker
  purpose: auto
- module: osint.secrets.secretfinder
  purpose: auto
- module: osint.secrets.githound
  purpose: auto
- module: osint.framework.reconng
  purpose: auto
- module: osint.framework.spiderfoot
  purpose: auto
- module: osint.framework.theharvester
  purpose: auto
- module: osint.framework.sn0int
  purpose: auto
- module: osint.framework.datasploit
  purpose: auto
- module: osint.framework.osintgram
  purpose: auto
- module: osint.framework.maigret
  purpose: auto
- module: osint.framework.sherlock
  purpose: auto
- module: osint.framework.social_analyzer
  purpose: auto
- module: osint.framework.whatsmyname
  purpose: auto
- module: osint.framework.holehe
  purpose: auto
- module: osint.framework.infoga
  purpose: auto
- module: osint.framework.h8mail
  purpose: auto
- module: osint.framework.ghunt
  purpose: auto
- module: osint.framework.twint
  purpose: auto
- module: osint.framework.snoop
  purpose: auto
- module: osint.framework.blackbird
  purpose: auto
- module: osint.framework.userrecon
  purpose: auto
- module: osint.framework.mosint
  purpose: auto
- module: osint.framework.osintsh
  purpose: auto
- module: osint.meta.metagoofil
  purpose: auto
- module: osint.meta.exiftool
  purpose: auto
- module: osint.meta.pdfid
  purpose: auto
- module: osint.cloud.cloudbrute
  purpose: auto
- module: osint.cloud.s3cario
  purpose: auto
- module: osint.cloud.s3cruze
  purpose: auto
- module: osint.cloud.s3dns
  purpose: auto
- module: osint.cloud.cloud_enum
  purpose: auto
- module: osint.util.anew
  purpose: auto
- module: osint.util.gf
  purpose: auto
- module: osint.util.uro
  purpose: auto
- module: osint.util.unfurl
  purpose: auto
- module: osint.util.qsreplace
  purpose: auto
- module: osint.util.notify
  purpose: auto
- module: osint.intel.misp
  purpose: auto
- module: osint.intel.opencti
  purpose: auto
- module: osint.intel.wazuh
  purpose: auto
- module: osint.intel.shuffle
  purpose: auto
- module: osint.web.webanalyze
  purpose: auto
- module: osint.web.retirejs
  purpose: auto
- module: osint.web.cdncheck
  purpose: auto
- module: osint.web.uncover
  purpose: auto
- module: osint.web.cvemap
  purpose: auto
- module: osint.web.notify
  purpose: auto
- module: osint.content.fdsploit
  purpose: auto
- module: osint.content.liffy
  purpose: auto
- module: osint.content.lfi_enum
  purpose: auto
- module: osint.content.lfisuite
  purpose: auto
- module: osint.graphql.inql
  purpose: auto
- module: osint.graphql.graphqlmap
  purpose: auto
- module: osint.graphql.clairvoyance
  purpose: auto
- module: osint.smuggling.smuggler
  purpose: auto
- module: osint.ssrf.ssrfmap
  purpose: auto
- module: osint.ssrf.gopherus
  purpose: auto
- module: osint.ssrf.httprebind
  purpose: auto
- module: osint.secrets.keyhacks
  purpose: auto
- module: osint.util.cuttcdn
  purpose: auto
- module: osint.util.hakip2host
  purpose: auto
- module: osint.util.jsmon
  purpose: auto
- module: osint.util.related_domains
  purpose: auto
- module: osint.user.whatsmyname
  purpose: auto
- module: osint.user.sherlock
  purpose: auto
- module: osint.user.maigret
  purpose: auto
- module: osint.user.socialscan
  purpose: auto
- module: osint.user.namechk
  purpose: auto
- module: osint.user.nexfil
  purpose: auto
- module: osint.email.holehe
  purpose: auto
- module: osint.email.infoga
  purpose: auto
- module: osint.email.h8mail
  purpose: auto
- module: osint.email.mosint
  purpose: auto
- module: osint.email.theharvester
  purpose: auto
- module: osint.social.twint
  purpose: auto
- module: osint.social.osintgram
  purpose: auto
- module: osint.social.toutatis
  purpose: auto
- module: osint.social.instaloader
  purpose: auto
- module: osint.framework.osintframework
  purpose: auto
- module: osint.dork.pagodo
  purpose: auto
- module: osint.search.searxng
  purpose: auto
- module: osint.paste.pastehunter
  purpose: auto
- module: osint.intel.intelowl
  purpose: auto
